# Generated by Django 3.1.5 on 2022-05-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('copies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('movie', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='mysite.movie')),
                ('user', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
            ],
        ),
    ]
